name: Test MCP Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Pull Datalust Seq Docker image
        run: docker pull datalust/seq

      - name: Run Datalust Seq Docker container
        run: docker run -d --name seq -p 5341:80 datalust/seq

      - name: Build MCP server
        run: dotnet build src/McpDatalustSeq.csproj

      - name: Run unit and integration tests
        run: dotnet test tests/McpDatalustSeq.Tests.csproj

      - name: Stop and remove Datalust Seq Docker container
        run: docker stop seq && docker rm seq
